[package]
name = "simumo_derive"
version = "0.1.0"
authors = ["Jeremie Bigras-Dunberry <bigjerbd@gmail.com>"]
edition = "2018"

[lib]
proc-macro=true


[dependencies]
syn = "0.15"
quote = "0.6.11"
proc-macro2 = "0.4"

