[package]
name = "rts_logger"
version = "0.1.0"
authors = ["Jeremie Bigras-Dunberry <bigjerbd@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.89"
erased-serde = "0.3.9"
serde_json = "1.0.39"
csv="1.0.5"
lazy_static = "1.3.0"