generals:
  clock_dt: 0.10
  end_time:
    val: 1200
  debugger:
    use: true
    width: 360
    height: 360

  random_speed: true
  seed: 055c1509-cf2e-499a-9c79-e85ace6e654d

map:
  type: CartFileMap
  path: etc/square_graph.json

systems:

  clock:
    type: StandardClock

  mobility:
    type: StandardMobility

  physic:
    type: Acceleration

  spawner:
    type: Frequency
    min: 1
    max: 3
    start_locations:
      - 0
    end_locations:
      - 5
