generals:
  clock_dt: 1.0
  end_time:
    val: 3000
  debugger:
    use: true
    width: 720
    height: 720

  random_speed: true
  seed: 055c1509-cf2e-499a-9c79-e85ace6e654d

map:
  type: PolarFileMap
  path: etc/tokyo_graph.json

systems:
  agents:
    - type: Accelerating

  clock:
    type: StandardClock

  controls: []

  logger:
    type: CsvLogger
    directory: "log_results"
    files: []

  mobility:
    type: StandardMobility

  physic:
    type: Acceleration



  #spawner:
  #  type: Frequency
  #  min: 10
  #  max: 20
  #  start_locations:
  #    - 31337279
  #  end_locations:
  #    - 31337279



entities:
  - id: car01
    type: vehicle
    position: [[5175583094, 5175583093], 0.5]
    destination: [[2669891200, 1032271065], 0.25]
    speed: 2
  - id: car02
    type: vehicle
    position: [[2643972537, 2643972535], 0.5]
    destination: [[1733695007, 1733695009], 0.25]
    speed: 2
  - id: car02
    type: vehicle
    position: [[1733695007, 1733695009], 0.5]
    destination: [[31300478, 569035381], 0.25]
    speed: 3

