city: "sherbrooke"
logs:
    directory: "logs"
    metrics:
        - name: "Vitesse Automobiles"
          logName: "sherbrooke_sample.ndjson"
          unit: "MeterPerSecond"
          unitLabel: "mètre par seconde"
legends:
    - red: 0
      green: 255
      blue: 0
    - red: 255
      green: 255
      blue: 0
    - red: 255
      green: 0
      blue: 0

